export const ENGLISH_PORTFOLIO_KEYWORDS = [
  'Digital Product Designer',
  'Product Designer Saudi Arabia',
  'UX Designer Saudi Arabia',
  'UI UX Designer',
  'UX Designer',
  'UI Designer',
  'Digital Product Design',
  'Product UX',
  'User Experience Design',
  'User Interface Design',
  'Web Designer',
  'Web Design',
  'Responsive Web Design',
  'UX Strategy',
  'Systems Thinking',
  'Information Architecture',
  'User Research',
  'Wireframing',
  'Prototyping',
  'Usability Testing',
  'Interaction Design',
  'Design Systems',
  'Accessibility',
  'WCAG',
  'Digital Governance',
  'Digital Government Authority',
  'DGA',
  'DGA compliance',
  'Developer Handoff',
  'Generative AI',
  'AI-assisted design',
  'AI workflows',
  'Enterprise UX',
  'Workflow Design',
  'Saudi Arabia',
] as const;

export const ARABIC_PORTFOLIO_KEYWORDS = [
  'مصمم منتجات رقمية',
  'مصمم تجربة مستخدم',
  'مصمم واجهات',
  'مصمم UI UX',
  'تصميم المنتجات الرقمية',
  'تجربة المستخدم',
  'تجربة المستخدم UX',
  'واجهة المستخدم',
  'واجهة المستخدم UI',
  'تصميم مواقع',
  'تصميم ويب',
  'تصميم الويب المتجاوب',
  'UI/UX',
  'UX Design',
  'UI Design',
  'Responsive Web Design',
  'UX Strategy',
  'التفكير بالأنظمة',
  'هندسة المعلومات',
  'Information Architecture',
  'أبحاث المستخدم',
  'User Research',
  'Wireframing',
  'Prototyping',
  'اختبار قابلية الاستخدام',
  'Usability Testing',
  'تصميم التفاعل',
  'Interaction Design',
  'أنظمة التصميم',
  'Design Systems',
  'إمكانية الوصول',
  'Accessibility',
  'WCAG',
  'الحوكمة الرقمية',
  'هيئة الحكومة الرقمية',
  'DGA',
  'Developer Handoff',
  'Generative AI',
  'AI-assisted design',
  'سير العمل الرقمي',
  'Product Design Saudi Arabia',
  'UX Designer Saudi Arabia',
  'Saudi Arabia',
] as const;
